server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://bqrrkmrlijplpm:baa42e4994b6608c7b120241a7be1760032f73b51ee77494fadef960d023bd5e@ec2-54-163-97-228.compute-1.amazonaws.com:5432/d9q60cogrvsqma
    username: bqrrkmrlijplpm
    password: baa42e4994b6608c7b120241a7be1760032f73b51ee77494fadef960d023bd5e
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend